//! Bulk data tables for the BC6H block packer: per-mode endpoint
//! significant-bit counts, the bit-layout programs that scatter endpoint bits
//! into each of the 14 BC6H modes, and the 32 two-subset partition patterns
//! (the first 32 BC7 patterns, with anchor texels flagged).

// Anchor flags are stored in decimal and the per-mode bit-layout programs are
// concatenated into one linear table, indexed through BC6H_LAYOUT_OFFSETS.

/// One step of a BC6H mode's bit-layout program: which endpoint value to read
/// (`comp` 0-2 = R/G/B, 3 = partition pattern; `index`
/// = subset*2 + low/high) and which of its bits to emit. `first_bit == -1`
/// emits the single bit `last_bit`; otherwise the run between `first_bit` and
/// `last_bit` inclusive is emitted, reversed when `first_bit > last_bit`.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Bc6hBitLayout {
    pub comp: i8,
    pub index: i8,
    pub last_bit: i8,
    pub first_bit: i8,
}

/// Endpoint significant-bit counts per BC6H mode: `[mode]` yields base bits
/// then per-channel delta bits (direct bits for the non-delta modes 9 and 10).
/// Modes 0-9 are 2-subset, 10-13 are 1-subset.
pub static BC6H_MODE_SIG_BITS: [[u8; 4]; 14] = [
    [10, 5, 5, 5],
    [7, 6, 6, 6],
    [11, 5, 4, 4],
    [11, 4, 5, 4],
    [11, 4, 4, 5],
    [9, 5, 5, 5],
    [8, 6, 5, 5],
    [8, 5, 6, 5],
    [8, 5, 5, 6],
    [6, 6, 6, 6],
    [10, 10, 10, 10],
    [11, 9, 9, 9],
    [12, 8, 8, 8],
    [16, 4, 4, 4],
];

/// The bit-layout programs for all 14 BC6H modes, flattened: each mode's steps
/// run to a `comp == -1` sentinel, and [`BC6H_LAYOUT_OFFSETS`] locates each
/// mode's first step.
pub static BC6H_BIT_LAYOUTS: [Bc6hBitLayout; 260] = [
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 6,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 6,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 6,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 0,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 1,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 2,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 3,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 5,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 3,
        last_bit: 4,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 3,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 2,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 2,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 3,
        last_bit: 5,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 3,
        index: -1,
        last_bit: 4,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 8,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: -1,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: 11,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: 11,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 7,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: 11,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 9,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 0,
        index: 0,
        last_bit: 10,
        first_bit: 15,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 1,
        index: 0,
        last_bit: 10,
        first_bit: 15,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 1,
        last_bit: 3,
        first_bit: 0,
    },
    Bc6hBitLayout {
        comp: 2,
        index: 0,
        last_bit: 10,
        first_bit: 15,
    },
    Bc6hBitLayout {
        comp: -1,
        index: 0,
        last_bit: 0,
        first_bit: 0,
    },
];

/// First [`BC6H_BIT_LAYOUTS`] index of each mode. The values follow from the
/// `comp == -1` sentinels that terminate each mode's program in the flattened
/// table; a unit test rederives them by scanning, so a regenerated table with
/// different mode lengths fails the test instead of silently misindexing.
/// (Spelled out rather than const-evaluated: on the crate's MSRV a const fn
/// cannot read a static.)
pub static BC6H_LAYOUT_OFFSETS: [usize; 14] = [
    0, 21, 46, 66, 88, 110, 131, 152, 175, 198, 223, 230, 240, 250,
];

/// The 32 BC6H two-subset partition patterns, flattened to one row per pattern
/// scanline: texel `i` of pattern `p` is
/// `[p * 4 + i / 4][i % 4]`. The low bit is the subset index; bit 7 flags an
/// anchor texel, whose weight is stored with one less bit.
pub static BC6H_2SUBSET_PATTERNS: [[u8; 4]; 128] = [
    [128, 0, 1, 1],
    [0, 0, 1, 1],
    [0, 0, 1, 1],
    [0, 0, 1, 129],
    [128, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 129],
    [128, 1, 1, 1],
    [0, 1, 1, 1],
    [0, 1, 1, 1],
    [0, 1, 1, 129],
    [128, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 0, 1, 1],
    [0, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 1, 129],
    [128, 0, 1, 1],
    [0, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 129],
    [128, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 1, 129],
    [128, 0, 0, 1],
    [0, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [1, 1, 1, 129],
    [128, 0, 0, 0],
    [1, 0, 0, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 129],
    [128, 1, 129, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [129, 0, 0, 0],
    [1, 1, 1, 0],
    [128, 1, 129, 1],
    [0, 0, 1, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0],
    [128, 0, 129, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [128, 0, 0, 0],
    [1, 0, 0, 0],
    [129, 1, 0, 0],
    [1, 1, 1, 0],
    [128, 0, 0, 0],
    [0, 0, 0, 0],
    [129, 0, 0, 0],
    [1, 1, 0, 0],
    [128, 1, 1, 1],
    [0, 0, 1, 1],
    [0, 0, 1, 1],
    [0, 0, 0, 129],
    [128, 0, 129, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0],
    [128, 0, 0, 0],
    [1, 0, 0, 0],
    [129, 0, 0, 0],
    [1, 1, 0, 0],
    [128, 1, 129, 0],
    [0, 1, 1, 0],
    [0, 1, 1, 0],
    [0, 1, 1, 0],
    [128, 0, 129, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 0],
    [1, 1, 0, 0],
    [128, 0, 0, 1],
    [0, 1, 1, 1],
    [129, 1, 1, 0],
    [1, 0, 0, 0],
    [128, 0, 0, 0],
    [1, 1, 1, 1],
    [129, 1, 1, 1],
    [0, 0, 0, 0],
    [128, 1, 129, 1],
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [1, 1, 1, 0],
    [128, 0, 129, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 0, 0],
];
#[cfg(test)]
mod offset_tests {
    use super::{BC6H_BIT_LAYOUTS, BC6H_LAYOUT_OFFSETS};

    /// The hand-spelled offsets must match a sentinel scan of the table.
    #[test]
    fn layout_offsets_match_sentinel_scan() {
        let mut ofs = [0usize; 14];
        let mut mode = 1;
        for (i, step) in BC6H_BIT_LAYOUTS.iter().enumerate() {
            if step.comp == -1 && mode < 14 {
                ofs[mode] = i + 1;
                mode += 1;
            }
        }
        assert_eq!(ofs, BC6H_LAYOUT_OFFSETS);
    }
}
